# Generated by Django 5.0.14 on 2026-07-12 06:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('points', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('initials', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('course', models.PositiveSmallIntegerField()),
                ('group_name', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('at_risk', 'At Risk'), ('top_reserve', 'Top Reserve'), ('expelled', 'Expelled')], default='active', max_length=20)),
                ('total_score', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_score', 'name'],
                'indexes': [models.Index(fields=['group_name'], name='students_st_group_n_9e0169_idx'), models.Index(fields=['course'], name='students_st_course_639de9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('science', 'Science'), ('project', 'Project'), ('extracurricular', 'Extracurricular')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('points', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('week_index', models.PositiveSmallIntegerField()),
                ('value', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'week_index')},
            },
        ),
    ]
