# Generated by Django 5.0.14 on 2026-07-12 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_score', models.FloatField()),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('academic', 'Academic'), ('enhanced', 'Enhanced'), ('achievement', 'Achievement')], max_length=20)),
            ],
        ),
    ]
