# Generated by Django 5.2.16 on 2026-07-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='allow_ai_chat',
            field=models.BooleanField(default=False),
        ),
    ]
