# Generated by Django 5.0.14 on 2026-07-12 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('participant_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='scoring.scoringlog')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_participants', to='students.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scoringparticipant',
            constraint=models.UniqueConstraint(fields=('log', 'student'), name='unique_scoring_participant'),
        ),
    ]
