# Generated by Django 5.2.16 on 2026-07-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_change_required_loginattempt_mfadevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycode',
            name='code_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='recoverycode',
            constraint=models.UniqueConstraint(fields=('user', 'code_hash'), name='unique_recovery_code_per_user'),
        ),
    ]
